import { describe, expect, it } from "vitest";
import { deriveProjectName, scanFiles } from "../shared/scanner";
import { cipherchatExpected, cipherchatStyleFiles } from "./fixtures/cipherchat-style";

describe("shared scanner contract", () => {
  it("derives a usable project name for blank-name archive scans", () => {
    expect(deriveProjectName("", "CipherChat6-main (1).zip")).toBe("CipherChat6 main (1)");
    expect(deriveProjectName(undefined, "")).toBe("Uploaded archive");
    expect(deriveProjectName("  My project  ", "other.zip")).toBe("My project");
  });
  it("flags explainable AI-likelihood signals without claiming authorship", () => {
    const generatedSource = [
      "// Here is a robust implementation",
      "// This function handles edge cases",
      "// implementation details are documented",
      "// Generated by an assistant",
      "// This class provides a comprehensive workflow",
      "const result = eval(input);",
      "// TODO: improve robust handling",
      "const veryLongLine = '" + "x".repeat(140) + "';",
      "const anotherVeryLongLine = '" + "y".repeat(140) + "';",
      "const thirdVeryLongLine = '" + "z".repeat(140) + "';",
    ].join("\n");
    const generated = scanFiles("generated", [{ path: "src/service.ts", content: generatedSource }]);
    const signal = generated.aiSignals[0];
    expect(signal?.score).toBeGreaterThanOrEqual(65);
    expect(signal?.confidence).toBe("high");
    expect(signal?.reasons.length).toBeGreaterThan(1);
    expect(signal?.lineStart).toBeGreaterThan(0);
    expect(signal?.lineEnd).toBeGreaterThanOrEqual(signal?.lineStart ?? 0);
    expect(signal?.evidence).toContain("Here is");
    expect(signal?.scoreBreakdown.phrasing).toBe(25);
    expect(signal?.verification).toContain("Review");
    expect(signal?.remediation).toContain("human review");
    expect(scanFiles("ordinary", [{ path: "main.py", content: "x = 1\\nprint(x)" }]).aiSignals).toEqual([]);
  });
  it("detects deterministic risks with exact file and line references", () => {
    const report = scanFiles("fixture", [{ path: "src/main.py", content: 'API_KEY = "secret-value-123"\nvalue = eval(input())\n# TODO: rotate key' }]);
    expect(report.schemaVersion).toBe("1.0");
    expect(report.languages).toEqual(["python"]);
    expect(report.findings.some((item) => item.ruleId === "SEC001" && item.file === "src/main.py" && item.line === 1 && item.severity === "critical")).toBe(true);
    expect(report.findings.some((item) => item.title === "Dynamic code execution" && item.line === 2)).toBe(true);
    expect(report.summary.critical).toBe(1);
    expect(report.findings[0]?.severity).toBe("critical");
    expect(report.qualityScore.score).toBe(9.6);
    expect(report.qualityScore.findingsConsidered).toBe(1);
    expect(report.qualityScore.basis).toContain("security risk");
  });
  it("scores clean code highly and quality issues lower without treating security as quality", () => {
    const clean = scanFiles("clean", [{ path: "main.py", content: "def add(left, right):\n    return left + right\n\nprint(add(1, 2))" }]);
    const needsWork = scanFiles("needs-work", [{ path: "main.py", content: "# TODO: make this robust\ntry:\n    print(value)\nexcept:\n    pass" }]);
    const secretOnly = scanFiles("secret-only", [{ path: "main.py", content: 'API_KEY = "secret-value-123456"' }]);
    expect(clean.qualityScore.score).toBe(10);
    expect(clean.qualityScore.label).toBe("excellent");
    expect(needsWork.qualityScore.score).toBeLessThan(10);
    expect(needsWork.qualityScore.breakdown.hygiene).toBeGreaterThan(0);
    expect(secretOnly.qualityScore.score).toBe(10);
  });
  it("does not flag safe library execution or non-security randomness", () => {
    const report = scanFiles("safe-context", [
      { path: "src/compressor.ts", content: "await ffmpeg.exec(['-i', inputName, outputName]);" },
      { path: "src/profile.ts", content: "const username = 'user-' + Math.random();" },
      { path: "src/reactions.ts", content: "if (reaction && Math.random() > 0.25) return null;" },
    ]);
    expect(report.findings.filter((item) => item.title === "Dynamic code execution")).toEqual([]);
    expect(report.findings.filter((item) => item.title === "Non-cryptographic randomness")).toEqual([]);
  });
  it("preserves shell/process true positives within the documented language scope", () => {
    const report = scanFiles("shell-positive", [
      { path: "unsafe.c", content: "system(user_input);" },
      { path: "unsafe.cpp", content: "popen(command, \"r\");" },
      { path: "unsafe.py", content: "import os\\nos.system(command)" },
      { path: "safe.ts", content: "System (label);\\nawait ffmpeg.exec(args);" },
    ]);
    const shellFindings = report.findings.filter((item) => item.title === "Shell command execution");
    expect(shellFindings.map((item) => item.file)).toEqual(["unsafe.c", "unsafe.cpp", "unsafe.py"]);
    expect(report.findings.some((item) => item.file === "safe.ts" && item.title === "Shell command execution")).toBe(false);
  });
  it("keeps known CipherChat safe patterns free of security findings and bounds true positives", () => {
    const report = scanFiles("cipherchat-safe-fixture", cipherchatStyleFiles);
    const safeSecurityFindings = report.findings.filter((item) => cipherchatExpected.securitySafeFiles.includes(item.file) && item.category === "security");
    expect(report.filesScanned).toBe(cipherchatExpected.filesScanned);
    expect(safeSecurityFindings).toEqual([]);
    expect(report.findings.some((item) => item.file === cipherchatExpected.truePositiveFile && item.title === "Shell command execution")).toBe(true);
    expect(report.findings.some((item) => item.file === cipherchatExpected.secretFile && item.ruleId === "SEC001")).toBe(true);
    expect(report.findings.some((item) => item.file === cipherchatExpected.secretFile && item.title === "Dynamic code execution")).toBe(true);
    expect(report.summary.critical).toBe(cipherchatExpected.maxCritical);
    expect(report.summary.high).toBeLessThanOrEqual(cipherchatExpected.maxHigh);
    expect(report.summary.medium).toBeLessThanOrEqual(cipherchatExpected.maxMedium);
  });
  it("keeps exact source lines and both locations for duplicate findings", () => {
    const repeated = "const responseMessage = createResponse(statusCode, userMessage, requestId, correlationId, retryAfter, securityContext, auditContext);";
    const report = scanFiles("evidence", [{ path: "src/one.ts", content: repeated }, { path: "src/two.ts", content: repeated }]);
    const duplicate = report.findings.find((item) => item.ruleId === "DUP001");
    expect(duplicate?.snippet).toBe(repeated);
    expect(duplicate?.line).toBe(1);
    expect(duplicate?.related).toMatchObject({ file: "src/one.ts", line: 1, snippet: repeated, context: { startLine: 1, lines: [repeated] } });
    const secret = scanFiles("source-line", [{ path: "src/config.py", content: 'API_KEY = "secret-value-123456"' }]).findings[0];
    expect(secret?.snippet).toContain("API_KEY");
  });
  it("flags randomness when the same file handles security material", () => {
    const report = scanFiles("security-context", [{ path: "src/auth.ts", content: "const token = process.env.TOKEN;\nconst nonce = Math.random();" }]);
    expect(report.findings.some((item) => item.title === "Non-cryptographic randomness" && item.line === 2)).toBe(true);
  });
  it("scans JavaScript and TypeScript using the shared report shape", () => {
    const report = scanFiles("web-project", [{ path: "src/app.ts", content: 'const token = "secret-value-123";\nconst result = eval(input);' }, { path: "src/client.jsx", content: "function render() { return <div />; }" }]);
    expect(report.filesScanned).toBe(2);
    expect(report.languages).toEqual(["typescript", "javascript"]);
    expect(report.findings.some((item) => item.file === "src/app.ts" && item.line === 1)).toBe(true);
  });
  it("scans C++ and Java using the same report shape", () => {
    const report = scanFiles("multi", [{ path: "a.cpp", content: "char* x; strcpy(x, input);" }, { path: "Token.java", content: 'String password = "password-123456";' }]);
    expect(report.filesScanned).toBe(2);
    expect(report.languages).toEqual(["cpp", "java"]);
    expect(report.findings.every((item) => item.file && item.line > 0 && item.remediation)).toBe(true);
  });
});
