import { describe, expect, it } from "vitest";
import { scanFiles, type ScanInputFile, type SupportedLanguage } from "../shared/scanner";

type Case = { language: SupportedLanguage; extension: string; safe: string; risky: string; comment: string };

const cases: Case[] = [
  { language: "c", extension: "c", safe: "int add(int a, int b) { return a + b; }", risky: "void run(char *cmd) { system(cmd); }", comment: "// system(user_input);" },
  { language: "cpp", extension: "cpp", safe: "int add(int a, int b) { return a + b; }", risky: "void run(const char *cmd) { popen(cmd, \"r\"); }", comment: "// popen(user_input, \"r\");" },
  { language: "python", extension: "py", safe: "def add(a, b):\n    return a + b", risky: "def run(value):\n    return eval(value)", comment: "# eval(user_input)" },
  { language: "java", extension: "java", safe: "class Add { int add(int a, int b) { return a + b; } }", risky: "class Run { void run(String value) { Runtime.getRuntime().exec(value); } }", comment: "// Runtime.getRuntime().exec(userInput);" },
  { language: "java", extension: "kt", safe: "fun add(a: Int, b: Int) = a + b", risky: "fun run(value: String) = Runtime.getRuntime().exec(value)", comment: "// Runtime.getRuntime().exec(userInput)" },
  { language: "javascript", extension: "js", safe: "export function add(a, b) { return a + b; }", risky: "export function run(value) { return eval(value); }", comment: "// eval(userInput);" },
  { language: "typescript", extension: "ts", safe: "export const add = (a: number, b: number) => a + b;", risky: "export const run = (value: string) => eval(value);", comment: "// eval(userInput);" },
];

function file(path: string, content: string): ScanInputFile { return { path, content }; }

function corpus(round: number): ScanInputFile[] {
  const repeatedLine = `const repeatedWorkflow = "${"stable reusable workflow data ".repeat(8)}";`;
  const aiSample = [
    "// Here is a robust implementation",
    "// This function handles edge cases",
    "// Generated by an assistant",
    "// TODO: make robust",
    "export function explain(value: string) {",
    "  return value.trim();",
    "}",
  ].join("\\n");
  return cases.flatMap((item, index) => [
    file(`round-${round}/safe-${index}.${item.extension}`, item.safe),
    file(`round-${round}/risky-${index}.${item.extension}`, item.risky),
    file(`round-${round}/comment-${index}.${item.extension}`, item.comment),
    file(`round-${round}/ui-${index}.${item.extension}`, "const label = 'user-' + Math.random();"),
    file(`round-${round}/duplicate-a-${index}.ts`, repeatedLine),
    file(`round-${round}/duplicate-b-${index}.ts`, repeatedLine),
    file(`round-${round}/ai-${index}.ts`, aiSample),
  ]);
}

describe("long small-file stress validation", () => {
  it("keeps language detection, true positives, comments, and safe contexts stable across many files", () => {
    const files = Array.from({ length: 40 }, (_, round) => corpus(round)).flat();
    const report = scanFiles("small-file-stress", files);
    expect(report.filesScanned).toBe(40 * cases.length * 7);
    expect(new Set(report.languages)).toEqual(new Set(cases.map((item) => item.language)));
    expect(report.findings.filter((item) => item.file.includes("comment-") || item.file.includes("ui-") && item.title === "Non-cryptographic randomness")).toEqual([]);
    expect(report.findings.some((item) => item.ruleId === "DUP001")).toBe(true);
    expect(report.aiSignals.some((signal) => signal.file.includes("ai-") && signal.score >= 35)).toBe(true);
    for (const item of cases) {
      expect(report.findings.filter((finding) => finding.file.endsWith(`risky-${cases.indexOf(item)}.${item.extension}`))).not.toEqual([]);
    }
    expect(report.qualityScore.score).toBeGreaterThanOrEqual(0);
    expect(report.qualityScore.score).toBeLessThanOrEqual(10);
    expect(report.findings.every((finding) => finding.line > 0 && finding.file && finding.ruleId && finding.remediation)).toBe(true);
  });

  it("produces identical findings and quality scores for repeated scans of the same small corpus", () => {
    const files = corpus(99);
    const first = scanFiles("repeat-small", files);
    const second = scanFiles("repeat-small", files);
    expect(first.findings).toEqual(second.findings);
    expect(first.summary).toEqual(second.summary);
    expect(first.qualityScore).toEqual(second.qualityScore);
    expect(first.aiSignals).toEqual(second.aiSignals);
  });
});
