import AdmZip from "adm-zip";
import { scanFiles, type ScanInputFile } from "../shared/scanner";

const durationMs = Number(process.env.STRESS_DURATION_MS ?? 3_600_000);
const apiUrl = process.env.CODESHIELD_SERVER ?? "http://127.0.0.1:3000/api/trpc";
const startedAt = new Date();
const started = Date.now();
let localIterations = 0;
let apiRequests = 0;
let pastedApiRequests = 0;
let filesScanned = 0;
let failures = 0;
let falsePositiveViolations = 0;
let lineEvidenceFailures = 0;
let deterministicMismatches = 0;
let totalApiLatency = 0;
let maxApiLatency = 0;
let lastError = "";

const files: ScanInputFile[] = [
  { path: "src/add.py", content: "def add(a, b):\n    return a + b" },
  { path: "src/unsafe.c", content: "void run(char *cmd) { system(cmd); }" },
  { path: "src/unsafe.cpp", content: "void copy(char *a, const char *b) { strcpy(a, b); }" },
  { path: "src/Run.java", content: "class Run { void run(String value) { Runtime.getRuntime().exec(value); } }" },
  { path: "src/App.kt", content: "fun add(a: Int, b: Int) = a + b" },
  { path: "src/ui.js", content: "export const id = Math.random();" },
  { path: "src/App.tsx", content: "// Here is a robust implementation\n// Generated by an assistant\n// TODO: make robust\nexport function App() { return <div />; }" },
  { path: "src/duplicate-a.ts", content: `const repeatedWorkflow = "${"stable reusable workflow data ".repeat(8)}";` },
  { path: "src/duplicate-b.ts", content: `const repeatedWorkflow = "${"stable reusable workflow data ".repeat(8)}";` },
  { path: "docs/comment.py", content: "# eval(user_input)\n# system(user_input)" },
];

function localCheck() {
  const first = scanFiles(`timed-local-${localIterations}`, files);
  const second = scanFiles(`timed-local-${localIterations}`, files);
  filesScanned += first.filesScanned;
  if (JSON.stringify(first.findings) !== JSON.stringify(second.findings) || JSON.stringify(first.qualityScore) !== JSON.stringify(second.qualityScore) || JSON.stringify(first.aiSignals) !== JSON.stringify(second.aiSignals)) deterministicMismatches++;
  if (!first.findings.some((item) => item.title === "Shell command execution")) failures++;
  if (first.findings.some((item) => item.file === "docs/comment.py" && item.category === "security")) falsePositiveViolations++;
  localIterations++;
}

async function apiCheck() {
  const zip = new AdmZip();
  for (const item of files) zip.addFile(item.path, Buffer.from(item.content));
  const body = { json: { projectName: "timed-small-file-stress", files: [], archiveBase64: zip.toBuffer().toString("base64"), archiveName: "timed-small-files.zip" } };
  const requestStarted = Date.now();
  try {
    const response = await fetch(`${apiUrl}/scanner.run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json() as any;
    const latency = Date.now() - requestStarted;
    totalApiLatency += latency; maxApiLatency = Math.max(maxApiLatency, latency); apiRequests++;
    const report = result.result?.data?.json ?? result;
    if (!response.ok || result.error || report.filesScanned !== files.length || !report.qualityScore) throw new Error(`invalid API report/status ${response.status}`);
    if (!report.findings.some((item: any) => item.title === "Shell command execution")) failures++;
    if (report.findings.some((item: any) => item.file === "docs/comment.py" && item.category === "security")) falsePositiveViolations++;
    if (report.findings.some((item: any) => typeof item.snippet !== "string" || item.snippet.length === 0 || (item.ruleId === "DUP001" && (!item.related || item.related.snippet !== item.snippet)))) lineEvidenceFailures++;
  } catch (error) { failures++; lastError = error instanceof Error ? error.message : String(error); }
}

async function pastedApiCheck() {
  const pastedSource = 'API_KEY = "stress-secret-value-123456"\nvalue = eval(user_input)';
  const body = { json: { projectName: "timed-pasted-stress", files: [{ path: "src/input.py", content: pastedSource }] } };
  try {
    const response = await fetch(`${apiUrl}/scanner.run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json() as any;
    pastedApiRequests++;
    const report = result.result?.data?.json ?? result;
    const secret = report.findings?.find((item: any) => item.ruleId === "SEC001");
    const dynamic = report.findings?.find((item: any) => item.title === "Dynamic code execution");
    if (!response.ok || result.error || report.filesScanned !== 1 || secret?.line !== 1 || secret?.snippet !== 'API_KEY = "stress-secret-value-123456"' || dynamic?.line !== 2 || dynamic?.snippet !== "value = eval(user_input)") lineEvidenceFailures++;
  } catch (error) { failures++; lastError = error instanceof Error ? error.message : String(error); }
}

while (Date.now() - started < durationMs) {
  localCheck();
  await apiCheck();
  await pastedApiCheck();
  if ((localIterations + apiRequests + pastedApiRequests) % 100 === 0) {
    console.log(JSON.stringify({ at: new Date().toISOString(), localIterations, apiRequests, pastedApiRequests, filesScanned, failures, falsePositiveViolations, lineEvidenceFailures, deterministicMismatches, avgApiLatencyMs: apiRequests ? Math.round(totalApiLatency / apiRequests) : 0, maxApiLatencyMs: maxApiLatency }));
  }
}

console.log(JSON.stringify({ startedAt: startedAt.toISOString(), endedAt: new Date().toISOString(), elapsedMs: Date.now() - started, durationTargetMs: durationMs, localIterations, apiRequests, pastedApiRequests, filesScanned, failures, falsePositiveViolations, lineEvidenceFailures, deterministicMismatches, avgApiLatencyMs: apiRequests ? Math.round(totalApiLatency / apiRequests) : 0, maxApiLatencyMs: maxApiLatency, lastError }, null, 2));
if (failures || falsePositiveViolations || lineEvidenceFailures || deterministicMismatches) process.exitCode = 1;
